title: Digital Library of Integral Ecology
description: A tutorial series on building a knowledge graph for ecology
# theme: minima
markdown: kramdown
highlighter: rouge
input: GFM

kramdown:
  auto_ids: true

github: https://github.com/clirdlf/dlie_knowledge_graph
linked_in: https://www.linkedin.com/company/6203386/

baseurl: "/dlie_knowledge_graph" # Leave blank unless using a custom subpath

permalink: pretty

name: Wayne Graham
email: wayne.graham@gmail.com

postcss:
  cache: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-postcss

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - .jekyll-cache