title: Digital Library of Integral Ecology
description: A tutorial series on building a knowledge graph for ecology
theme: minima
markdown: kramdown
baseurl: "/dlie_knowledge_graph" # Leave blank unless using a custom subpath

minima:
  social_links:
    github: your-username
    linkedin: your-handle